### ISSUE TITLE
Does islandora_compound_batch work as expected with Islandora 7.x-1.9?

### ISSUE THREAD

**Issue by MarcusBarnes** [MarcusBarnes/islandora_compound_batch#18]
Run sanity tests to confirm that islandora_compound_batch works as expected with the recently released [Islandora 7.x-1.9](http://islandora.ca/content/its-alive-islandora-7x-19-release-announcement), creating tickets should any issues arise.

**Comment by cdeaneGit** [comment]
Back in March, I made a ticket for myself about documenting the islandora_solution_pack_compound.

https://jira.duraspace.org/browse/ISLANDORA-1948
islandora_solution_pack_compound needs more documentation

I am especially interested in batch ingest.

In April Melissa Anez sent me an email approving addition of Batch Ingest Compound Objects to the wiki page: https://wiki.duraspace.org/display/ISLANDORA/How+to+Batch+Ingest+Files
(I had already contributed a section.)

I was also tasked in my day job to test the Marcus Barnes islandora_compound_batch.

So I forked a copy from his repository, read the README (great!) and hoped to start testing as soon as 7.x-1.19 was released.

And then of course the day job had all sorts of deadlines that I must honor before I start testing.  

My test input data includes a folio postcard (22 images/ 22 mods files) that I put online several years ago using the original compound object module.  They display correctly as compound objects (manual re-order) and the details display (the mods) changes each time to match the image.

Publically available online at: 
http://digital.lib.utk.edu/collections/islandora/object/pcard00%3A100233

I still hope to test the islandora_compound_batch because it looks much easier to implement than current method.

cheers!
cricket!

**Comment by mjordan** [comment]
@MarcusBarnes I'm processing a batch of compound objects today so can test with 7.x-1.9.

**Comment by MarcusBarnes** [comment]
Related to this, I'd like to add some unit tests and fixtures for various parts of the module functionality as appropriate and as possible.

**Comment by mjordan** [comment]
My tests yesterday were successful other than I was ingesting large image child objects, which failed to render in the OpenSeadragon viewer. I loaded the same files using Islandora Batch and with the same result, so I don't believe the failure to render was Compound Batch's fault. I'll test again with some basic images later today.

I agree, some tests would be a great addition. I was thinking about adding tests to Islandora Datastream Crud so I'd be happy to work on tests for Compound Batch as well.

**Comment by mjordan** [comment]
@MarcusBarnes @cdeaneGit I just ingested two compound objects in 7.x-1.9 and everything worked as expected.

**Comment by mjordan** [comment]
Can this be closed?
